project_name: streamingfast-client
release:
  github:
    owner: streamingfast
    name: streamingfast-client
  draft: true
  name_template: '{{.Tag}}'
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/sf
  binary: sf
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: macOS
    linux: linux
    386: i386
    amd64: x86_64
  files:
  - LICENSE
  - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - cmd: keybase
    args:
      - sign
      - --infile
      - $artifact
      - --binary
      - --outfile
      - $signature
      - --detached
    signature: ${artifact}.sig
    artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
