project_name: cream-track-hacker

env_files:
  github_token: ~/.config/goreleaser/github_token

release:
  github:
    owner: streamingfast
    name: cream-track-hacker
  draft: true
  name_template: '{{.Tag}}'
  extra_files:
    - glob: ./release/**/*

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

builds:
- id: tracker
  binary: tracker
  main: ./cmd/tracker
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
- id: tracker-osx
  binary: tracker
  main: ./cmd/tracker
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  hooks:
    post: gon gon.hcl

archives:
- replacements:
    darwin: macOS
    linux: linux
    386: i386
    amd64: x86_64
  files:
  - LICENSE
  - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
